config/routes.rb
Rails.application.routes.draw do
  resources :video
  get '/videos' => 'video#index'
  root 'home#home'
  get '/contact' => 'home#contact'
  post 'request_contact', to: 'home#request_contact'
 

end

app/models/video.rb
class Video < ActiveRecord::Base
    
    validates :title, presence: true
    validates :title, uniqueness: true
    validates :about, presence: true
    
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def home
  end
  
  def contact
    @time = Time.now
  end
  
  def request_contact
    name = params[:name]
    email = params[:email]
    telephone = params[:telephone]
    message = params[:message]
    
    if email.blank?
      flash[:alert] = I18n.t('home.request_contact.no_email')
    else
      ContactMailer.contact_email(email, name, telephone, message).deliver_now
      flash[:notice] = I18n.t('home.request_contact.email_sent')
    end
    
    redirect_to root_path
    
  end
  
end

app/controllers/video_controller.rb
class VideoController < ApplicationController
  before_action :set_video, only: [:show, :edit, :update, :destroy]

  # GET /video
  # GET /video.json
  def index
    @video = Video.all
  end

  # GET /video/1
  # GET /video/1.json
  def show
  end

  # GET /video/new
  def new
    @video = Video.new
  end

  # GET /video/1/edit
  def edit
  end

  # POST /video
  # POST /video.json
  def create
    @video = Video.new(video_params)

    respond_to do |format|
      if @video.save
        format.html { redirect_to @video, notice: 'Video was successfully created.' }
        format.json { render :show, status: :created, location: @video }
      else
        format.html { render :new }
        format.json { render json: @video.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /video/1
  # PATCH/PUT /video/1.json
  def update
    respond_to do |format|
      if @video.update(video_params)
        format.html { redirect_to @video, notice: 'Video was successfully updated.' }
        format.json { render :show, status: :ok, location: @video }
      else
        format.html { render :edit }
        format.json { render json: @video.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /video/1
  # DELETE /video/1.json
  def destroy
    @video.destroy
    respond_to do |format|
      format.html { redirect_to video_url, notice: 'Video was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_video
      @video = Video.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def video_params
      params.require(:video).permit(:title, :about)
    end
end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
  before_action :set_video, only: [:show, :edit, :update, :destroy]

  # GET /videos
  # GET /videos.json
  def index
    @videos = Video.all
  end

  # GET /videos/1
  # GET /videos/1.json
  def show
  end

  # GET /videos/new
  def new
    @video = Video.new
  end

  # GET /videos/1/edit
  def edit
  end

  # POST /videos
  # POST /videos.json
  def create
    @video = Video.new(video_params)

    respond_to do |format|
      if @video.save
        format.html { redirect_to @video, notice: 'Video was successfully created.' }
        format.json { render :show, status: :created, location: @video }
      else
        format.html { render :new }
        format.json { render json: @video.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /videos/1
  # PATCH/PUT /videos/1.json
  def update
    respond_to do |format|
      if @video.update(video_params)
        format.html { redirect_to @video, notice: 'Video was successfully updated.' }
        format.json { render :show, status: :ok, location: @video }
      else
        format.html { render :edit }
        format.json { render json: @video.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /videos/1
  # DELETE /videos/1.json
  def destroy
    @video.destroy
    respond_to do |format|
      format.html { redirect_to videos_url, notice: 'Video was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_video
      @video = Video.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def video_params
      params.require(:video).permit(:title, :about)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/videos_helper.rb
module VideosHelper
end

app/views/home/contact.html.haml
%h1= t('.title')
%p= t('.contact_us')

%p
    = link_to 'Home', root_url

= form_tag request_contact_path, method: 'post' do
    = label_tag :name, t('.name')
    = text_field_tag :name, '', title: t('.enter_name'), size: 50
    
    = label_tag :email, t('.email')
    = email_field_tag :email, '', title: t('.enter_email')
    
    = label_tag :telephone, t('.telephone')
    = telephone_field_tag :telephone, '', title: t('.enter_telephone')
    
    = label_tag :message, t('.message')
    = text_field_tag :message, '', title: t('.enter_message'), size: 100
    
    = submit_tag t('.submit')

app/views/home/home.html.haml
%h1= t('.title')
%p= t('.welcome')

%p
    = link_to 'Contact', contact_url

app/views/layouts/application.html.haml
!!!

%html
  %head
    %meta{'charset' => 'utf-8'}
    %meta{'http-equiv' => 'x-ua-compatible', 'content' => 'ie=edge'}

    %title= t('app_title')

    %meta{'name' => 'description', 'content' => t('app_description')}
    %meta{'name' => 'viewport', 'content' => 'width=device-width, initial-scale=1'}

    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = javascript_include_tag 'modernizr'
    = csrf_meta_tags

  %body
  
    - flash.each do |key, value|
      = content_tag :div, content_tag(:p, value), id: "#{key}" unless value.blank?

    = render 'shared/header'

    = yield

    = render 'shared/footer'

app/views/shared/_footer.html.haml
%footer
    %p!= "&copy; Alex Brown #{Time.now.year}"

app/views/shared/_header.html.haml
%header
    %p
    = link_to 'Home', root_url
    = + " | "
    = link_to 'Contact', contact_url
    = + " | "
    = link_to 'Videos', videos_url
    

app/views/video/_form.html.haml
= form_for @video do |f|
  - if @video.errors.any?
    #error_explanation
      %h2= "#{pluralize(@video.errors.count, "error")} prohibited this video from being saved:"
      %ul
        - @video.errors.full_messages.each do |message|
          %li= message

  .field
    = f.label :title
    = f.text_field :title
  .field
    = f.label :about
    = f.text_area :about
  .actions
    = f.submit 'Save'

app/views/video/edit.html.haml
%h1 Editing video

= render 'form'

= link_to 'Show', @video
\|
= link_to 'Back', video_path

app/views/video/index.html.haml
%h1 Listing videos

%table
  %thead
    %tr
      %th Title
      %th About
      %th
      %th
      %th

  %tbody
    - @video.each do |video|
      %tr
        %td= video.title
        %td= video.about
        %td= link_to 'Show', video
        %td= link_to 'Edit', edit_video_path(video)
        %td= link_to 'Destroy', video, method: :delete, data: { confirm: 'Are you sure?' }

%br

= link_to 'New Video', new_video_path

app/views/video/new.html.haml
%h1 New video

= render 'form'

= link_to 'Back', video_path

app/views/video/show.html.haml
%p#notice= notice

%p
  %b Title:
  = @video.title
%p
  %b About:
  = @video.about

= link_to 'Edit', edit_video_path(@video)
\|
= link_to 'Back', video_path

app/views/videos/edit.html.haml
%h1 Editing video

= render 'form'

= link_to 'Show', @video
\|
= link_to 'Back', videos_path

app/views/videos/index.html.haml
%h1 Listing videos

%table
  %thead
    %tr
      %th Title
      %th About
      %th
      %th
      %th

  %tbody
    - @videos.each do |video|
      %tr
        %td= video.title
        %td= video.about
        %td= link_to 'Show', video
        %td= link_to 'Edit', edit_video_path(video)
        %td= link_to 'Destroy', video, method: :delete, data: { confirm: 'Are you sure?' }

%br

= link_to 'New Video', new_video_path

app/views/videos/new.html.haml
%h1 New video

= render 'form'

= link_to 'Back', videos_path

app/views/videos/show.html.haml
%p#notice= notice

%p
  %b Title:
  = @video.title
%p
  %b About:
  = @video.about

= link_to 'Edit', edit_video_path(@video)
\|
= link_to 'Back', videos_path